name: Continuous Integration

on:
  pull_request:
    branches: [development]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.12.0
      - run: yarn install --immutable --immutable-cache --check-cache
      - run: yarn lint
      - run: yarn build
